In [1]:
import pandas as pd
from sklearn import datasets
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn import metrics
import numpy as np

In [7]:
boston = datasets.load_boston()
# print(boston.data.shape[0]/15)
X = boston.data
y = boston.target
boston.feature_names

array(['CRIM', 'ZN', 'INDUS', 'CHAS', 'NOX', 'RM', 'AGE', 'DIS', 'RAD',
       'TAX', 'PTRATIO', 'B', 'LSTAT'], dtype='<U7')

In [4]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3)

In [5]:
model = RandomForestRegressor(n_estimators=300)
model.fit(X_train,y_train)
y_pred = model.predict(X_train)
y_pred1 = model.predict(X_test)

In [11]:
model.feature_importances_

array([0.05897474, 0.0018684 , 0.0066144 , 0.00066963, 0.01578907,
       0.46595676, 0.01666125, 0.05893559, 0.00579747, 0.01602262,
       0.01642828, 0.01166461, 0.32461719])

In [8]:
print("MSE Train:",metrics.mean_squared_error(y_train, y_pred))
print("MSE Test:",metrics.mean_squared_error(y_test, y_pred1))

MSE Train: 1.5080475797238002
MSE Test: 12.632243395467858


In [9]:
print("Score Train:" ,model.score(X_train, y_train))
print("Score Test:" ,model.score(X_test, y_test))

Score Train: 0.9818539380964976
Score Test: 0.8551552387715088


In [10]:
from sklearn.model_selection import cross_val_score
model = RandomForestRegressor(n_estimators=100)
r = cross_val_score(model, X_train, y_train, cv=10)
np.mean(r)

0.8472501567108329

In [8]:
from sklearn.model_selection import cross_val_score
model = RandomForestRegressor(n_estimators=300)
r = cross_val_score(model, X_train, y_train, cv=5)
np.mean(r)

0.800610260815249

In [11]:
model.fit(X_train, y_train)
display(model.predict(X[10,:].reshape(1,-1)))
# display(iris.target_names)
display(y[10])

array([17.73])

15.0

In [12]:
X[10,:]

array([2.2489e-01, 1.2500e+01, 7.8700e+00, 0.0000e+00, 5.2400e-01,
       6.3770e+00, 9.4300e+01, 6.3467e+00, 5.0000e+00, 3.1100e+02,
       1.5200e+01, 3.9252e+02, 2.0450e+01])

In [13]:
X[10,:].reshape(1,-1)

array([[2.2489e-01, 1.2500e+01, 7.8700e+00, 0.0000e+00, 5.2400e-01,
        6.3770e+00, 9.4300e+01, 6.3467e+00, 5.0000e+00, 3.1100e+02,
        1.5200e+01, 3.9252e+02, 2.0450e+01]])